/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/Lucy/Desktop/Interactive-Story/client/public/abandoned_storefront.glb
Author: Scans Planet (https://sketchfab.com/ScansPlanet)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abandoned-storefront-0fc0da9dddd040c38864635bc21e82c1
Title: Abandoned storefront
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { AxesHelper } from 'three'

function StoreAbandonned(props) {
  const { nodes, materials } = useGLTF('/abandoned_storefront.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.model_tex_u1_v1_0.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_1.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_2.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_3.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_4.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_5.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_6.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_7.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_8.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_9.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_10.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_11.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.model_tex_u1_v1_0_12.geometry} material={materials.tex_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/abandoned_storefront.glb')
export default StoreAbandonned;