/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/Lucy/Desktop/Interactive-Story/client/public/strossmayerova_facade.glb
Author: gbmgroup (https://sketchfab.com/gbmgroup)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/strossmayerova-facade-a889577e4d7b4f0aa636388f15553769
Title: Strossmayerova facade
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Facade(props) {
  const { nodes, materials } = useGLTF('/strossmayerova_facade.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -509.05, 597.59]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Facade_Scann_Dacimated} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Facade_Scann_Dacimated} />
      </group>
    </group>
  )
}

useGLTF.preload('/strossmayerova_facade.glb')
export default Facade;