/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/Lucy/Desktop/Interactive-Story/client/public/wall.glb
Author: 3Dystopia (https://sketchfab.com/Dystopia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/building-scan-no-6-1ad2a22607354887bdb5da8e753f6a97
Title: Building scan No. 6
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Wall(props) {
  const { nodes, materials } = useGLTF('/wall.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['batiment6_lowpoly.002']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['batiment6_lowpoly.002']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['batiment6_lowpoly.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/wall.glb')
export default Wall;