/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 E:\Developpement\Interactive Studio\Interactive-StoryV3\Interactive-Story\client\public\Motel\anime_starry_night.glb
Author: fangzhangmnm (https://sketchfab.com/fangzhangmnm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anime-starry-night-db0952ccd1ee4c77a1a07709b3d4f4f0
Title: Anime Starry Night
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Test1(props) {
  const { nodes, materials } = useGLTF('/anime_starry_night.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} scale={500} />
    </group>
  )
}

useGLTF.preload('/anime_starry_night.glb')

export default Test1;
