/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 E:\Developpement\Interactive Studio\Interactive-StoryV3\Interactive-Story\client\public\Motel\forest.glb
Author: rhfqcntrkf (https://sketchfab.com/rhfqcntrkf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/forest-9153c2b370934758bf14c395abe36b27
Title: Forest
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Forest(props) {
  const { nodes, materials } = useGLTF('/forest.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Green_Elka} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Green_Elka} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Green_Elka} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Green_Elka} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Green_Elka} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Green_sosna.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Green_sosna.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Kust_1} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Kust_2} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Paporotnik} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Wood_tree.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Wood_tree.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/forest.glb')

export default Forest;
