/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 E:\Developpement\Interactive Studio\Interactive-StoryV3\Interactive-Story\client\public\MotelProjetAdvanced.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

 function MotelObjAdvanced(props) {
  const { nodes, materials } = useGLTF('/MotelProjetAdvanced.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-5.98, -1.49, 24.68]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.08, 0.01, 0.02]}>
        <mesh geometry={nodes.SM_GlassFence2_M_StovePlate_0.geometry} material={materials.M_StovePlate} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-5.98, -1.49, 24.68]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.08, 0.01, 0.02]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.SM_GlassFence2_M_StovePlate_0001.geometry} material={materials['M_StovePlate.001']} />
          <mesh geometry={nodes.SM_GlassFence2_M_StovePlate_0002.geometry} material={materials['M_StovePlate.001']} position={[-250.66, -1.39, 9.35]} rotation={[Math.PI, -0.04, Math.PI]} />
          <mesh geometry={nodes.SM_GlassFence2_M_StovePlate_0003.geometry} material={materials['M_StovePlate.001']} position={[-254.11, -17.07, -1496.22]} rotation={[0, 1.57, 0]} scale={[12.1, 1, 1]} />
          <mesh geometry={nodes.SM_GlassFence2_M_StovePlate_0004.geometry} material={materials['M_StovePlate.001']} position={[-255.65, -15.93, -3523.9]} rotation={[0, 1.57, 0]} scale={[8.03, 1, 1]} />
          <mesh geometry={nodes.SM_GlassFence2_M_StovePlate_0005.geometry} material={materials['M_StovePlate.001']} position={[-126.89, -35.46, -4454.79]} rotation={[0.02, -0.16, 0]} scale={[1.12, 1, 4.88]} />
        </group>
      </group>
      <group position={[18.97, 50.03, 264.76]} rotation={[-1.58, 0.01, 0.41]} scale={[20, 20, 30]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.39}>
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00000009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00004009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00014009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00018009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00026009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00028009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00029009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00031009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00032009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00033009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00038009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00041009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00043009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00044009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00046009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00047009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00048009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00049009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00050009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00051009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00053009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00054009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00057009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00058009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00060009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00062009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00064009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00067009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00069009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00071009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00072009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00073009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00075009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00077009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00080009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00084009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00085009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00086009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00087009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00092009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00095009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00096009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00100009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00102009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00105009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00108009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00109009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00111009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00113009_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00116007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00119007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00122007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00124007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00126007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00131007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00135007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00141007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00145007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00149007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00152007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00158007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00163007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00167007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00168007_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00174006_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00187004_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00189004_0'].geometry} material={materials['BuildingMat-00081.009']} />
            <mesh geometry={nodes['BuildingMesh-00000001_BuildingMat-00191004_0'].geometry} material={materials['BuildingMat-00081.009']} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.car_body.geometry} material={materials.MAIN} position={[12.24, -0.09, 3.86]} rotation={[Math.PI, -0.93, Math.PI]}>
        <mesh geometry={nodes.door_l.geometry} material={materials.MAIN} position={[0.91, 0.68, 0.64]}>
          <mesh geometry={nodes.win_door_l001.geometry} material={materials.WINDOW} position={[-0.15, 0.7, -0.73]} />
        </mesh>
        <mesh geometry={nodes.door_r.geometry} material={materials.MAIN} position={[-0.91, 0.68, 0.64]}>
          <mesh geometry={nodes.win_door_r001.geometry} material={materials.WINDOW} position={[0.15, 0.7, -0.73]} />
        </mesh>
        <mesh geometry={nodes.free_number.geometry} material={materials.MAIN} position={[0, 0.79, -1.77]} />
        <mesh geometry={nodes.interior.geometry} material={materials.MAIN} position={[0.94, 0.6, -0.07]} rotation={[0, 0, -Math.PI / 2]} scale={[0.44, 0.4, 0.4]} />
        <mesh geometry={nodes.wheel_bl.geometry} material={materials.MAIN} position={[0.78, 0.33, -1.24]} rotation={[0, 1.57, 0]} scale={0.32} />
        <mesh geometry={nodes.wheel_br.geometry} material={materials.MAIN} position={[-0.78, 0.33, -1.24]} rotation={[0, 1.57, 0]} scale={0.32} />
        <mesh geometry={nodes.wheel_fl.geometry} material={materials.MAIN} position={[0.78, 0.33, 1.07]} rotation={[0, 1.57, 0]} scale={0.32} />
        <mesh geometry={nodes.wheel_fr.geometry} material={materials.MAIN} position={[-0.78, 0.33, 1.07]} rotation={[0, 1.57, 0]} scale={0.32} />
        <mesh geometry={nodes.windows.geometry} material={materials.WINDOW} />
      </mesh>
      <mesh geometry={nodes.GroundTracks001.geometry} material={materials['GroundTracks.001']} position={[15.75, -0.13, 62.25]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.GroundTracks002.geometry} material={materials['GroundTracks.001']} position={[15.75, -0.13, -47.4]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.GroundTracks.geometry} material={materials.GroundTracks} position={[15.74, -0.22, 190.33]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[2.79, -0.22, -9.08]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.MotelSign_1.geometry} material={materials.SignLitLettering} />
        <mesh geometry={nodes.MotelSign_2.geometry} material={materials.MetalPatchy} />
        <mesh geometry={nodes.MotelSign_3.geometry} material={materials.Generator} />
      </group>
      <group position={[-6.06, -0.14, -2.41]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Dumpster.geometry} material={materials.DumpsterGarbage} />
        <mesh geometry={nodes.Dumpster_1.geometry} material={materials.Dumpster} />
      </group>
      <group position={[-5.91, -0.45, -4.77]} rotation={[Math.PI / 2, 0, -0.28]}>
        <mesh geometry={nodes.Dumpster.geometry} material={materials.DumpsterGarbage} />
        <mesh geometry={nodes.Dumpster_1.geometry} material={materials.Dumpster} />
      </group>
      <mesh geometry={nodes.WoodPallet_B.geometry} material={materials.Wood} position={[-4.86, 0.37, -0.33]} rotation={[Math.PI / 2, 1.34, 0]} />
      <mesh geometry={nodes.WoodPallet_A.geometry} material={materials.Wood} position={[-5.05, 0.37, -0.49]} rotation={[Math.PI / 2, 1.25, 0]} />
      <mesh geometry={nodes.DumpsterDoorLeft_B.geometry} material={materials.DumpsterCover} position={[-5.64, 1.6, -2.41]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DumpsterDoorRight_B.geometry} material={materials.DumpsterCover} position={[-5.64, 1.6, -2.41]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DumpsterDoorRight_A.geometry} material={materials.DumpsterCover} position={[-5.63, 1.38, -5.04]} rotation={[Math.PI / 2, 0, -0.27]} />
      <mesh geometry={nodes.TVAntenna.geometry} material={materials.MetalRough} position={[-3.76, 6.92, -5.78]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BeerBottle_A.geometry} material={materials.FoodPaintSafe} position={[3.24, 6.92, -6.42]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BeerBottle_B.geometry} material={materials.FoodPaintSafe} position={[3.19, 6.95, -6.37]} rotation={[Math.PI, -0.29, 0]} />
      <mesh geometry={nodes.BeerBottle_C.geometry} material={materials.FoodPaintSafe} position={[3.3, 6.95, -6.37]} rotation={[-Math.PI, 0.05, 0]} />
      <mesh geometry={nodes.WaterPipe.geometry} material={materials.WaterPipe} position={[0.01, -0.14, 8.45]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[3.78, 5.84, -6.16]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LampWallHanging.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.LampWallHanging_1.geometry} material={materials.Lamp} />
      </group>
      <group position={[-0.36, 5.84, -6.97]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.LampWallHanging.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.LampWallHanging_1.geometry} material={materials.Lamp} />
      </group>
      <group position={[3.78, 5.84, 7.72]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LampWallHanging.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.LampWallHanging_1.geometry} material={materials.Lamp} />
      </group>
      <group position={[-4.99, 5.84, 0.04]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.LampWallHanging.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.LampWallHanging_1.geometry} material={materials.Lamp} />
      </group>
      <mesh geometry={nodes.Bollard_A.geometry} material={materials.GasCan} position={[3.91, -0.14, -4.44]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_B.geometry} material={materials.GasCan} position={[3.91, -0.14, -3.53]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_C.geometry} material={materials.GasCan} position={[3.91, -0.14, -2.61]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_D.geometry} material={materials.GasCan} position={[3.91, -0.14, -1.69]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_E.geometry} material={materials.GasCan} position={[3.91, -0.14, -0.78]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_F.geometry} material={materials.GasCan} position={[3.91, -0.14, 0.14]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_G.geometry} material={materials.GasCan} position={[3.91, -0.14, 1.06]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_H.geometry} material={materials.GasCan} position={[3.91, -0.14, 1.97]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_I.geometry} material={materials.GasCan} position={[3.91, -0.14, 2.89]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_J.geometry} material={materials.GasCan} position={[3.91, -0.14, 3.81]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_K.geometry} material={materials.GasCan} position={[3.91, -0.14, 4.72]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_L.geometry} material={materials.GasCan} position={[3.91, -0.14, 5.64]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_M.geometry} material={materials.GasCan} position={[3.91, -0.14, 6.55]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bollard_N.geometry} material={materials.GasCan} position={[3.91, -0.14, 7.47]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-4.83, 1.1, 2.38]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LadderLock_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.LadderLock_2.geometry} material={materials.MetalDiamond} />
      </group>
      <mesh geometry={nodes.LadderOutdoor.geometry} material={materials.MetalShiny} position={[-4.96, -0.14, 2.38]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsShortSingle.geometry} material={materials.Wood} position={[2.79, -0.14, -6.25]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsShortSingle_B.geometry} material={materials.Wood} position={[2.79, -0.14, 9.3]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-1} />
      <mesh geometry={nodes.StairsFlatSingle_A.geometry} material={materials.Wood} position={[2.79, 0.86, -4.52]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsFlatSingle_B.geometry} material={materials.Wood} position={[2.79, 0.86, -2.79]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsFlatSingle_C.geometry} material={materials.Wood} position={[2.79, 0.86, -1.06]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsFlatSingle_D.geometry} material={materials.Wood} position={[2.79, 0.86, 0.66]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsFlatSingle_E.geometry} material={materials.Wood} position={[2.79, 0.86, 2.39]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsFlatSingle_F.geometry} material={materials.Wood} position={[2.79, 0.86, 4.12]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsFlatSingle_G.geometry} material={materials.Wood} position={[2.79, 0.86, 5.84]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsLongSingle.geometry} material={materials.Wood} position={[-3.34, 0.86, -7.34]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsShortDouble.geometry} material={materials.Wood} position={[-4, -0.14, -9.75]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsFlatSmall.geometry} material={materials.Wood} position={[-4, 0.86, -8.01]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsRailSingle.geometry} material={materials.Wood} position={[-4.63, 1.1, -7.36]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-3.73, -0.14, -7.34]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.StorageStairs_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.StorageStairs_2.geometry} material={materials.WoodBoards} />
      </group>
      <mesh geometry={nodes.StairsRailLong.geometry} material={materials.Wood} position={[2.47, 3.94, -7.96]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.StairsRailShort.geometry} material={materials.Wood} position={[3.4, 3.94, -7.32]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-3.55, -0.24, -7.35]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.TarpCoveredObject_1.geometry} material={materials.Dumpster} />
        <mesh geometry={nodes.TarpCoveredObject_2.geometry} material={materials.Tarp} />
      </group>
      <group position={[2.03, 3.94, -3.92]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.DoorRoom.geometry} material={materials.DoorRoom} />
        <mesh geometry={nodes.DoorRoom_1.geometry} material={materials.Brass} />
      </group>
      <group position={[2.03, 3.94, 0.13]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.DoorRoom.geometry} material={materials.DoorRoom} />
        <mesh geometry={nodes.DoorRoom_1.geometry} material={materials.Brass} />
      </group>
      <group position={[2.03, 3.94, 4.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.DoorRoom.geometry} material={materials.DoorRoom} />
        <mesh geometry={nodes.DoorRoom_1.geometry} material={materials.Brass} />
      </group>
      <group position={[2.03, 1.1, -3.92]} rotation={[-Math.PI / 2, 0, 1.12]} scale={-1}>
        <mesh geometry={nodes.DoorRoom.geometry} material={materials.DoorRoom} />
        <mesh geometry={nodes.DoorRoom_1.geometry} material={materials.Brass} />
      </group>
      <group position={[2.03, 1.1, 0.13]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.DoorRoom.geometry} material={materials.DoorRoom} />
        <mesh geometry={nodes.DoorRoom_1.geometry} material={materials.Brass} />
      </group>
      <group position={[2.03, 1.1, 4.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.DoorRoom.geometry} material={materials.DoorRoom} />
        <mesh geometry={nodes.DoorRoom_1.geometry} material={materials.Brass} />
      </group>
      <mesh geometry={nodes.BasementWindowFrame_A.geometry} material={materials.Concrete} position={[1.94, 0.22, -3.52]} rotation={[Math.PI / 2, -1.57, 0]} />
      <mesh geometry={nodes.BasementWindowFrame_B.geometry} material={materials.Concrete} position={[1.94, 0.22, -0.21]} rotation={[Math.PI / 2, -1.57, 0]} />
      <mesh geometry={nodes.BasementWindowFrame_C.geometry} material={materials.Concrete} position={[1.94, 0.22, 3.09]} rotation={[Math.PI / 2, -1.57, 0]} />
      <mesh geometry={nodes.BasementWindowFrame_D.geometry} material={materials.Concrete} position={[1.94, 0.22, 6.4]} rotation={[Math.PI / 2, -1.57, 0]} />
      <group position={[-4.4, 2.11, -6.58]} rotation={[Math.PI / 2, 0, 0.18]} scale={[1.03, 1, 1]}>
        <mesh geometry={nodes.DoorOffice_1.geometry} material={materials.OfficeDoor} />
        <mesh geometry={nodes.DoorOffice_2.geometry} material={materials.OfficeDoorWindow} />
      </group>
      <mesh geometry={nodes.WindowRoom_A.geometry} material={materials.FrostedGlass} position={[2.12, 5.06, -2.44]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowRoom_B.geometry} material={materials.FrostedGlass} position={[2.12, 5.06, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowRoom_C.geometry} material={materials.FrostedGlass} position={[2.12, 5.06, 5.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowRoom_D.geometry} material={materials.FrostedGlass} position={[2.12, 2.22, -2.44]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowRoom_E.geometry} material={materials.FrostedGlass} position={[2.12, 2.22, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowRoom_F.geometry} material={materials.FrostedGlass} position={[2.12, 2.22, 5.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowFrame_A.geometry} material={materials.Concrete} position={[2.12, 5.06, -2.44]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowFrame_B.geometry} material={materials.Concrete} position={[2.12, 5.06, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowFrame_C.geometry} material={materials.Concrete} position={[2.12, 5.06, 5.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowFrame_D.geometry} material={materials.Concrete} position={[2.12, 2.22, -2.44]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowFrame_E.geometry} material={materials.Concrete} position={[2.12, 2.22, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.WindowFrame_F.geometry} material={materials.Concrete} position={[2.12, 2.22, 5.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.03, 1, 1]} />
      <mesh geometry={nodes.DoorFrame_B.geometry} material={materials.Concrete} position={[2.07, 3.94, -3.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DoorFrame_C.geometry} material={materials.Concrete} position={[2.07, 3.94, 0.59]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DoorFrame_D.geometry} material={materials.Concrete} position={[2.07, 3.94, 4.65]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DoorFrame_E.geometry} material={materials.Concrete} position={[2.07, 1.1, -3.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DoorFrame_F.geometry} material={materials.Concrete} position={[2.07, 1.1, 0.59]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DoorFrame_G.geometry} material={materials.Concrete} position={[2.07, 1.1, 4.65]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DoorFrame_A.geometry} material={materials.Concrete} position={[2.07, 3.94, -5.68]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.DoorFrame_H.geometry} material={materials.Concrete} position={[-3.94, 1.1, -6.62]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <group position={[2.03, 3.94, -6.14]} rotation={[-Math.PI / 2, 0, 1.28]} scale={-1}>
        <mesh geometry={nodes.DoorSupply_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DoorSupply_2.geometry} material={materials.MetalDoor} />
      </group>
      <group position={[-0.16, -1.82, -2.94]} rotation={[-Math.PI / 2, 0, 1.85]} scale={-1}>
        <mesh geometry={nodes.DoorBasement_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DoorBasement_2.geometry} material={materials.MetalDoor} />
      </group>
      <mesh geometry={nodes.DoorFrameSmall.geometry} material={materials.Concrete} position={[0.3, -1.82, -2.99]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <group position={[-2.62, 1.1, -2.4]} rotation={[Math.PI / 2, 0, 1.59]}>
        <mesh geometry={nodes.DoorBathroom_1.geometry} material={materials.Brass} />
        <mesh geometry={nodes.DoorBathroom_2.geometry} material={materials.Concrete} />
      </group>
      <mesh geometry={nodes.DoorBathroomFrame.geometry} material={materials.Concrete} position={[-3.08, 1.1, -2.35]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.WindowBlinds.geometry} material={materials.Concrete} position={[2.02, 3.11, -1.83]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BasementWindow_A.geometry} material={materials.FrostedGlass} position={[1.94, 0.22, -3.52]} rotation={[Math.PI / 2, -1.57, 0]} />
      <mesh geometry={nodes.BasementWindow_B.geometry} material={materials.FrostedGlass} position={[1.94, 0.22, -0.21]} rotation={[Math.PI / 2, -1.57, 0]} />
      <mesh geometry={nodes.BasementWindow_C.geometry} material={materials.FrostedGlass} position={[1.94, 0.22, 3.09]} rotation={[Math.PI / 2, -1.57, 0]} />
      <mesh geometry={nodes.BasementWindow_D.geometry} material={materials.FrostedGlass} position={[1.94, 0.22, 6.4]} rotation={[Math.PI / 2, -1.57, 0]} />
      <group position={[2.03, 1.1, -4.39]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.InteriorWallRoom_1.geometry} material={materials.InteriorWall} />
        <mesh geometry={nodes.InteriorWallRoom_2.geometry} material={materials.Carpet} />
        <mesh geometry={nodes.InteriorWallRoom_3.geometry} material={materials.Tiles} />
      </group>
      <group position={[-2.91, 1.1, -3.96]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Toilet_1.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.Toilet_2.geometry} material={materials.FrostedGlass} />
      </group>
      <group position={[-4.48, 1.1, -4.39]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Shower_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.Shower_2.geometry} material={materials.ShowerTiles} />
        <mesh geometry={nodes.Shower_3.geometry} material={materials.FabricPattern} />
      </group>
      <group position={[-4.45, 1.08, -2.94]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.BathroomSink_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.BathroomSink_2.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.BathroomSink_3.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-3.91, 1.43, -2.49]} rotation={[Math.PI / 2, 0, 0.36]}>
        <mesh geometry={nodes.BathroomSinkDoorLeft_1.geometry} material={materials.Brass} />
        <mesh geometry={nodes.BathroomSinkDoorLeft_2.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-3.91, 1.43, -3.39]} rotation={[Math.PI / 2, 0, -0.22]}>
        <mesh geometry={nodes.BathroomSinkDoorRight_1.geometry} material={materials.Brass} />
        <mesh geometry={nodes.BathroomSinkDoorRight_2.geometry} material={materials.WoodDark} />
      </group>
      <mesh geometry={nodes.RadiatorHeater.geometry} material={materials.MetalShiny} position={[1.95, 1.08, -1.36]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.TableDining.geometry} material={materials.WoodDark} position={[1.11, 1.1, -1.63]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0.47, 1.1, -1.16]} rotation={[Math.PI / 2, 0, -0.41]}>
        <mesh geometry={nodes.ChairDining.geometry} material={materials.WoodDark} />
        <mesh geometry={nodes.ChairDining_1.geometry} material={materials.FabricSoft} />
      </group>
      <group position={[1.61, 1.1, -2.18]} rotation={[Math.PI / 2, 0, 2.28]}>
        <mesh geometry={nodes.ChairDining.geometry} material={materials.WoodDark} />
        <mesh geometry={nodes.ChairDining_1.geometry} material={materials.FabricSoft} />
      </group>
      <group position={[1.11, -0.34, 2.91]} rotation={[-Math.PI / 2, 0, -0.3]}>
        <mesh geometry={nodes.ChairDining.geometry} material={materials.WoodDark} />
        <mesh geometry={nodes.ChairDining_1.geometry} material={materials.FabricSoft} />
      </group>
      <group position={[1.11, -0.34, 3.53]} rotation={[-Math.PI / 2, 0, 0.07]}>
        <mesh geometry={nodes.ChairDining.geometry} material={materials.WoodDark} />
        <mesh geometry={nodes.ChairDining_1.geometry} material={materials.FabricSoft} />
      </group>
      <group position={[0.88, 2.97, -0.75]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Painting_1.geometry} material={materials.WoodDark} />
        <mesh geometry={nodes.Painting_2.geometry} material={materials.ClothesArt} />
      </group>
      <mesh geometry={nodes.Dresser.geometry} material={materials.WoodDark} position={[-0.6, 1.1, -1.12]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Dresser_B.geometry} material={materials.WoodDark} position={[1.41, -1.82, 3.31]} rotation={[Math.PI / 2, 0, -1.62]} />
      <group position={[-0.6, 1.79, -0.96]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.DresserDrawerTop.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DresserDrawerTop_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[1.53, -1.27, 1.98]} rotation={[1.58, -0.04, -1.31]}>
        <mesh geometry={nodes.DresserDrawerTop.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DresserDrawerTop_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-0.6, 1.13, -1.17]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.DresserDrawerBottom.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DresserDrawerBottom_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[1.45, -1.81, 2.17]} rotation={[Math.PI / 2, 0, -1.31]}>
        <mesh geometry={nodes.DresserDrawerBottom.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DresserDrawerBottom_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-0.6, 1.46, -0.85]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.DresserDrawerMiddle.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DresserDrawerMiddle_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[1.56, -1.54, 2.15]} rotation={[1.57, -0.02, -1.41]}>
        <mesh geometry={nodes.DresserDrawerMiddle.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.DresserDrawerMiddle_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-0.61, 2.09, -1.1]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.TV.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.TV_1.geometry} material={materials.TV} />
      </group>
      <group position={[1.45, -1.82, -2.08]} rotation={[Math.PI / 2, 0, -1.78]}>
        <mesh geometry={nodes.TV.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.TV_1.geometry} material={materials.TV} />
      </group>
      <mesh geometry={nodes.Nightstand.geometry} material={materials.WoodDark} position={[0.11, 1.1, -4.09]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Nightstand_B.geometry} material={materials.WoodDark} position={[1.32, -1.82, -0.35]} rotation={[Math.PI / 2, 0, 1.2]} />
      <group position={[0.11, 1.43, -4.1]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.NightstandDrawer.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.NightstandDrawer_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[0.65, -1.56, 0.75]} rotation={[2.11, 1.12, 2.57]}>
        <mesh geometry={nodes.NightstandDrawer.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.NightstandDrawer_1.geometry} material={materials.WoodDark} />
      </group>
      <group position={[0.22, 1.67, -4.17]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LampTable.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.LampTable_1.geometry} material={materials.LampBulb} />
      </group>
      <group position={[1.27, -1.24, 2.06]} rotation={[Math.PI / 2, 0, -1.31]}>
        <mesh geometry={nodes.LampTable.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.LampTable_1.geometry} material={materials.LampBulb} />
      </group>
      <mesh geometry={nodes.Telephone_B.geometry} material={materials.RoomProps} position={[0.28, 1.67, -3.95]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Telephone_A.geometry} material={materials.RoomProps} position={[-1.34, 1.84, -6.33]} rotation={[Math.PI / 2, 0, 0.27]} />
      <mesh geometry={nodes.ClothesFolded.geometry} material={materials.ClothesArt} position={[-0.84, 1.89, -1.24]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ClothesPile.geometry} material={materials.ClothesArt} position={[-0.6, 1.28, -1.17]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-1.07, 1.1, -4.37]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Bed_1.geometry} material={materials.FabricPattern} />
        <mesh geometry={nodes.Bed_2.geometry} material={materials.WoodDark} />
        <mesh geometry={nodes.Bed_3.geometry} material={materials.FabricSoft} />
      </group>
      <mesh geometry={nodes.AlarmClock.geometry} material={materials.RoomProps} position={[-0.05, 1.67, -4.16]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-2.51, 2, -3.45]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.ToiletpaperHolder_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.ToiletpaperHolder_2.geometry} material={materials.Concrete} />
      </group>
      <mesh geometry={nodes.BathroomMirror.geometry} material={materials.FrostedGlass} position={[-4.48, 2.58, -2.94]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BathroomLight.geometry} material={materials.BathroomLight} position={[-4.41, 3.2, -2.94]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-3.61, 1.1, -1.12]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Armoire_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.Armoire_2.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-4.41, 2.1, -1.39]} rotation={[Math.PI / 2, 0, -1.56]}>
        <mesh geometry={nodes.ArmoireDoorRight_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.ArmoireDoorRight_2.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-2.8, 2.1, -1.39]} rotation={[Math.PI / 2, 0, 2.45]}>
        <mesh geometry={nodes.ArmoireDoorLeft_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.ArmoireDoorLeft_2.geometry} material={materials.WoodDark} />
      </group>
      <mesh geometry={nodes.Safe.geometry} material={materials.FoodPaintSafe} position={[-3.26, 1.13, -1.11]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Pillow.geometry} material={materials.FabricSoft} position={[-3.14, 1.54, -1.11]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PillowFolded.geometry} material={materials.FabricSoft} position={[-3.35, 1.69, -1.05]} rotation={[Math.PI / 2, 0.46, 0]} />
      <group position={[-3.65, 2.72, -1.13]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Hangers_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Hangers_2.geometry} material={materials.MetalShiny} />
      </group>
      <mesh geometry={nodes.FridgeCabinet.geometry} material={materials.WoodDark} position={[-1.41, 1.1, -1.12]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-2.22, 1.1, -1.12]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CounterTop_1.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.CounterTop_2.geometry} material={materials.WoodDark} />
      </group>
      <group position={[-1.65, 1.63, -1.41]} rotation={[Math.PI / 2, 0, -1.88]}>
        <mesh geometry={nodes.RefrigeratorDoor_1.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.RefrigeratorDoor_2.geometry} material={materials.Appliances} />
      </group>
      <group position={[1.04, -1.32, -1.18]} rotation={[Math.PI / 2, 0, -1.27]}>
        <mesh geometry={nodes.RefrigeratorDoor_1.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.RefrigeratorDoor_2.geometry} material={materials.Appliances} />
      </group>
      <mesh geometry={nodes.Microwave_A.geometry} material={materials.Appliances} position={[-1.41, 2.3, -0.91]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Microwave_B.geometry} material={materials.Appliances} position={[1.62, -0.95, -1.35]} rotation={[Math.PI / 2, 0, -1.69]} />
      <mesh geometry={nodes.Refrigerator.geometry} material={materials.Appliances} position={[-1.41, 1.12, -1.18]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Refrigerator_B.geometry} material={materials.Appliances} position={[1.33, -1.83, -1.34]} rotation={[Math.PI / 2, 0, -1.27]} />
      <group position={[-1.41, 2.08, -0.86]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.FridgeCabinetDrawer_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.FridgeCabinetDrawer_2.geometry} material={materials.WoodDark} />
      </group>
      <mesh geometry={nodes.Sandwich.geometry} material={materials.FoodPaintSafe} position={[-1.54, 1.48, -1.11]} rotation={[Math.PI / 2, 0, -1.85]} />
      <mesh geometry={nodes.BeerBottle_D.geometry} material={materials.FoodPaintSafe} position={[-1.25, 1.45, -1.23]} rotation={[Math.PI / 2, 0, -1.42]} />
      <mesh geometry={nodes.Bible.geometry} material={materials.RoomProps} position={[0.17, 1.47, -3.82]} rotation={[Math.PI / 2, 0, 0.36]} />
      <group position={[3.47, 6.96, 0.67]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AwningLarge_1.geometry} material={materials.MetalPatchy} />
        <mesh geometry={nodes.AwningLarge_2.geometry} material={materials.FabricBlueSaturated} />
      </group>
      <group position={[-0.6, 6.96, -6.66]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AwningSmall_1.geometry} material={materials.MetalPatchy} />
        <mesh geometry={nodes.AwningSmall_2.geometry} material={materials.FabricBlueSaturated} />
      </group>
      <group position={[-4.59, 1.1, -6.58]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.InteriorWallOffice_1.geometry} material={materials.InteriorWall} />
        <mesh geometry={nodes.InteriorWallOffice_2.geometry} material={materials.Carpet} />
      </group>
      <mesh geometry={nodes.FileCabinet.geometry} material={materials.FileCabinet} position={[-0.85, 1.1, -6.58]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-2.06, 1.1, -6.2]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.TableFolding_1.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.TableFolding_2.geometry} material={materials.FoldingTable} />
      </group>
      <mesh geometry={nodes.FileCabinetDrawer_A.geometry} material={materials.FileCabinet} position={[-0.85, 2.13, -5.79]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.FileCabinetDrawer_B.geometry} material={materials.FileCabinet} position={[-0.85, 1.83, -5.88]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.FileCabinetDrawer_C.geometry} material={materials.FileCabinet} position={[-0.85, 1.52, -5.88]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.FileCabinetDrawer_D.geometry} material={materials.FileCabinet} position={[-0.85, 1.21, -5.63]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.CoffeeMachine.geometry} material={materials.CoffeeMachine} position={[-2.69, 1.84, -6.37]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Radio.geometry} material={materials.CleanerPapersRadioKey} position={[-0.84, 2.46, -6.16]} rotation={[Math.PI / 2, 0, 0.41]} />
      <group position={[-1.64, 1.93, -6.3]} rotation={[Math.PI / 2, 0, -0.61]}>
        <mesh geometry={nodes.CoffeeCup_1.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.CoffeeCup_2.geometry} material={materials.CoffeeMachine} />
      </group>
      <mesh geometry={nodes.PaperStacks.geometry} material={materials.CleanerPapersRadioKey} position={[-1.69, 1.84, -6.37]} rotation={[Math.PI / 2, 0, -0.09]} />
      <mesh geometry={nodes.ChairFolding.geometry} material={materials.FoldingChair} position={[-1.67, 1.1, -5.36]} rotation={[Math.PI / 2, 0, -0.41]} />
      <group position={[-2.08, 1.84, -6.13]} rotation={[Math.PI / 2, 0, -0.38]}>
        <mesh geometry={nodes.Clipboard_1.geometry} material={materials.FoodPaintSafe} />
        <mesh geometry={nodes.Clipboard_2.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.Clipboard_3.geometry} material={materials.CleanerPapersRadioKey} />
      </group>
      <mesh geometry={nodes.CoffeePot.geometry} material={materials.CoffeeMachine} position={[-2.68, 1.89, -6.29]} rotation={[Math.PI / 2, 0, -0.68]} />
      <mesh geometry={nodes.CorkBoard.geometry} material={materials.Corkboard} position={[-1.96, 2.41, -6.58]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.RoomKey_A.geometry} material={materials.CleanerPapersRadioKey} position={[-1.74, 2.25, -6.55]} rotation={[1.47, 0.21, 0.02]} />
      <mesh geometry={nodes.RoomKey_B.geometry} material={materials.CleanerPapersRadioKey} position={[-1.56, 2.25, -6.55]} rotation={[1.47, 0.21, 0.02]} />
      <mesh geometry={nodes.RoomKey_C.geometry} material={materials.CleanerPapersRadioKey} position={[-1.64, 2.17, -6.55]} rotation={[-1.67, 0.34, 0.03]} scale={-1} />
      <mesh geometry={nodes.OfficeLight.geometry} material={materials.Appliances} position={[-2.35, 3.32, -5.72]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[2.12, 0.68, 8]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.ExteriorWall_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.ExteriorWall_2.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.ExteriorWall_3.geometry} material={materials.PaintedBricks} />
      </group>
      <mesh geometry={nodes.ExteriorWallBasement.geometry} material={materials.PaintedBricks} position={[2.12, 0.68, 8]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[3.47, 3.94, 8]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.ExteriorWallSecondFloor_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.ExteriorWallSecondFloor_2.geometry} material={materials.PaintedBricks} />
      </group>
      <mesh geometry={nodes.Generator.geometry} material={materials.Generator} position={[-3.37, -1.82, 4.41]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.GeneratorExhaust.geometry} material={materials.MetalRough} position={[-3.38, -0.32, 5.31]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.GeneratorPowerBox.geometry} material={materials.MetalRough} position={[-4.39, -0.81, 2.42]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.GasCan_A.geometry} material={materials.GasCan} position={[-3.78, -1.63, 1.48]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.GasCan_B.geometry} material={materials.GasCan} position={[-4.08, -1.63, 1.34]} rotation={[Math.PI / 2, 0, 0.72]} />
      <mesh geometry={nodes.Shelves_A.geometry} material={materials.Wood} position={[-3.49, -1.82, 0.35]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Shelves_B.geometry} material={materials.Wood} position={[-3.49, -1.82, -2.86]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Shelves_C.geometry} material={materials.Wood} position={[-0.83, -1.82, -4.76]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle2Large.geometry} material={materials.BoxesStyle2} position={[-3.89, -1.63, -1.75]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle2Large_B.geometry} material={materials.BoxesStyle2} position={[0.71, 4.36, -5.21]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle2Small.geometry} material={materials.BoxesStyle2} position={[-3.89, -1.63, -2.3]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle2Small_B.geometry} material={materials.BoxesStyle2} position={[-1.41, 5.39, -5.35]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.BoxStyle2Medium.geometry} material={materials.BoxesStyle2} position={[-3.89, -0.78, -3.88]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle2Medium_B.geometry} material={materials.BoxesStyle2} position={[-1.41, 5.39, -6.2]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxPlastic_G.geometry} material={materials.plastic} position={[-3.9, 0.07, -3.95]} rotation={[Math.PI / 2, 0, -0.02]} />
      <mesh geometry={nodes.BoxPlastic_F.geometry} material={materials.plastic} position={[-3.9, 0.07, -3.31]} rotation={[Math.PI / 2, 0, 0.02]} />
      <mesh geometry={nodes.BoxPlastic_E.geometry} material={materials.plastic} position={[-3.9, 0.07, -2.51]} rotation={[Math.PI / 2, 0, 0.06]} />
      <mesh geometry={nodes.BoxPlastic_D.geometry} material={materials.plastic} position={[-3.9, 0.07, -1.84]} rotation={[Math.PI / 2, 0, -0.04]} />
      <mesh geometry={nodes.BoxPlastic_C.geometry} material={materials.plastic} position={[-3.9, 0.07, -0.74]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxPlastic_B.geometry} material={materials.plastic} position={[-3.9, 0.07, -0.07]} rotation={[Math.PI / 2, 0, -0.15]} />
      <mesh geometry={nodes.BoxPlastic_A.geometry} material={materials.plastic} position={[-3.9, 0.07, 0.83]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxPlastic_H.geometry} material={materials.plastic} position={[-1.17, 0.07, -3.76]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxPlastic_J.geometry} material={materials.plastic} position={[-1.25, -0.78, -3.76]} rotation={[Math.PI / 2, 0, -1.66]} />
      <mesh geometry={nodes.BoxPlastic_I.geometry} material={materials.plastic} position={[-1.25, -0.78, -5.18]} rotation={[Math.PI / 2, 0, -1.53]} />
      <mesh geometry={nodes.BoxPlastic_K.geometry} material={materials.plastic} position={[-0.4, 3.94, -5.2]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxPlastic_L.geometry} material={materials.plastic} position={[-0.4, 4.41, -5.2]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Toolbox.geometry} material={materials.Toolbox} position={[-3.85, -0.78, 1.38]} rotation={[Math.PI / 2, 0, -0.16]} />
      <mesh geometry={nodes.ToolboxLid.geometry} material={materials.Toolbox} position={[-3.96, -0.57, 1.4]} rotation={[-1.61, 0.24, -2.98]} />
      <mesh geometry={nodes.BoxStyle1_B.geometry} material={materials.BoxesStyle13} position={[-3.91, -1.63, -0.6]} rotation={[Math.PI / 2, 0, -0.12]} />
      <mesh geometry={nodes.BoxStyle1_A.geometry} material={materials.BoxesStyle13} position={[-3.91, -1.63, 0.34]} rotation={[Math.PI / 2, 0, 0.09]} />
      <mesh geometry={nodes.BoxStyle1_D.geometry} material={materials.BoxesStyle13} position={[-1.5, 4.66, -5.38]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle1_C.geometry} material={materials.BoxesStyle13} position={[-1.44, 3.94, -5.35]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle3Small.geometry} material={materials.BoxesStyle13} position={[-3.92, -0.78, -2.27]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle3Small_B.geometry} material={materials.BoxesStyle13} position={[0.65, 3.94, -5.18]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.BoxStyle2Long.geometry} material={materials.BoxesStyle2} position={[-3.82, -1.41, -2.89]} rotation={[1.23, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.BoxStyle2Long_B.geometry} material={materials.BoxesStyle2} position={[0.14, 4.89, -5.22]} rotation={[1.57, 0.02, 0]} />
      <group position={[-3.9, -0.78, -3.29]} rotation={[Math.PI / 2, 0, 0.36]}>
        <mesh geometry={nodes.BucketPlastic_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.BucketPlastic_2.geometry} material={materials.plastic} />
      </group>
      <mesh geometry={nodes.PaintCan_A.geometry} material={materials.PaintCan} position={[-3.95, -0.78, -0.7]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PaintCan_C.geometry} material={materials.PaintCan} position={[-4.07, -0.78, -0.86]} rotation={[Math.PI / 2, 0, 0.48]} />
      <mesh geometry={nodes.PaintCan_B.geometry} material={materials.PaintCan} position={[-3.89, -0.78, -0.9]} rotation={[Math.PI / 2, 0, -1.23]} />
      <mesh geometry={nodes.PaintCan_D.geometry} material={materials.PaintCan} position={[-3.98, -0.59, -0.82]} rotation={[Math.PI / 2, 0, 2.1]} />
      <mesh geometry={nodes.PaintTray.geometry} material={materials.FoodPaintSafe} position={[-3.88, -0.78, -0.36]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-4.01, -0.73, -0.34]} rotation={[Math.PI / 2, 0.15, 0]}>
        <mesh geometry={nodes.PaintRoller_1.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.PaintRoller_2.geometry} material={materials.Brass} />
        <mesh geometry={nodes.PaintRoller_3.geometry} material={materials.Carpet} />
      </group>
      <mesh geometry={nodes.PaintBrush.geometry} material={materials.FoodPaintSafe} position={[-3.72, -0.77, -0.84]} rotation={[Math.PI / 2, 0, -1.4]} />
      <mesh geometry={nodes.PipeStraight_B.geometry} material={materials.MetalRough} position={[-3.69, -0.75, 0.28]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PipeStraight_A.geometry} material={materials.MetalRough} position={[-3.62, -0.75, 0.25]} rotation={[Math.PI / 2, 0, 0.08]} />
      <mesh geometry={nodes.PipeStraight_C.geometry} material={materials.MetalRough} position={[-3.74, -0.75, 0.42]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PipeBend_B.geometry} material={materials.MetalRough} position={[-3.84, -0.75, 0.35]} rotation={[-Math.PI / 2, -0.46, -Math.PI]} />
      <mesh geometry={nodes.PipeBend_A.geometry} material={materials.MetalRough} position={[-3.79, -0.75, 0.53]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PipeT_A.geometry} material={materials.MetalRough} position={[-3.83, -0.75, -0.01]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.PipeT_B.geometry} material={materials.MetalRough} position={[-3.88, -0.75, -0.01]} rotation={[Math.PI / 2, 0.8, 0]} />
      <mesh geometry={nodes.PipeT_C.geometry} material={materials.MetalRough} position={[-3.97, -0.75, -0.01]} rotation={[Math.PI / 2, 0, -0.72]} />
      <mesh geometry={nodes.WoodScrap_D.geometry} material={materials.Wood} position={[-3.92, -0.72, 0.47]} rotation={[1.49, 0, 0]} />
      <mesh geometry={nodes.WoodScrap_A.geometry} material={materials.Wood} position={[-4.16, -0.75, 0.43]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.WoodScrap_B.geometry} material={materials.Wood} position={[-4.11, -0.7, 0.42]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.WoodScrap_C.geometry} material={materials.Wood} position={[-4.04, -0.75, 0.39]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.WoodScrapLarge.geometry} material={materials.WoodDark} position={[-4.03, -0.67, 0.46]} rotation={[Math.PI / 2, 0, 0.1]} />
      <mesh geometry={nodes.CleaningSpray.geometry} material={materials.CleanerPapersRadioKey} position={[-1.04, -1.63, -3.38]} rotation={[Math.PI / 2, 0, -2.75]} />
      <mesh geometry={nodes.CleaningSpray_B.geometry} material={materials.CleanerPapersRadioKey} position={[1.58, 3.94, -5.1]} rotation={[Math.PI / 2, 0, -0.92]} />
      <mesh geometry={nodes.Broom.geometry} material={materials.Broom} position={[-0.81, -0.94, -3.21]} rotation={[1.42, -0.17, -1.57]} />
      <mesh geometry={nodes.Broom_B.geometry} material={materials.Broom} position={[1.58, 4.82, -4.99]} rotation={[1.84, -0.09, -1.29]} />
      <group position={[-1.32, -1.82, -3.03]} rotation={[Math.PI / 2, 0, -0.97]}>
        <mesh geometry={nodes.Mop_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Mop_2.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Mop_3.geometry} material={materials.Mop} />
      </group>
      <group position={[1.8, 3.94, -5.08]} rotation={[Math.PI / 2, 0, 0.77]}>
        <mesh geometry={nodes.Mop_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Mop_2.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Mop_3.geometry} material={materials.Mop} />
      </group>
      <mesh geometry={nodes.BoxStyle3Damaged.geometry} material={materials.BoxesStyle13} position={[-1.19, -1.63, -4.02]} rotation={[Math.PI / 2, 0, -0.06]} />
      <mesh geometry={nodes.BoxStyle3Damaged_B.geometry} material={materials.BoxesStyle13} position={[-1.43, 4.66, -6.13]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BoxStyle3Clean.geometry} material={materials.BoxesStyle13} position={[-1.19, -1.63, -5.32]} rotation={[Math.PI / 2, 0, -0.05]} />
      <mesh geometry={nodes.BoxStyle3Clean_B.geometry} material={materials.BoxesStyle13} position={[-1.47, 3.94, -6.15]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.MattressDirty_C.geometry} material={materials.MatrtressDirty} position={[0.84, -1.82, 6.15]} rotation={[Math.PI / 2, 0, 0.12]} />
      <mesh geometry={nodes.MattressDirty_B.geometry} material={materials.MatrtressDirty} position={[0.77, -1.51, 6.15]} rotation={[Math.PI / 2, 0, 3.11]} />
      <mesh geometry={nodes.MattressDirty_A.geometry} material={materials.MatrtressDirty} position={[0.74, -1.2, 6.51]} rotation={[Math.PI / 2, 0, 1.59]} />
      <mesh geometry={nodes.BedFrame.geometry} material={materials.WoodDark} position={[0.46, -0.66, -0.68]} rotation={[-1, -1.1, -2.62]} />
      <group position={[-1.14, 0.69, 0.54]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LightHangingBulb.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.LightHangingBulb_1.geometry} material={materials.LampBulb} />
      </group>
      <group position={[-1.14, 0.69, 5.2]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LightHangingBulb.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.LightHangingBulb_1.geometry} material={materials.LampBulb} />
      </group>
      <group position={[0.09, 6.55, -5.69]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.LightHangingBulb.geometry} material={materials.Asphalt} />
        <mesh geometry={nodes.LightHangingBulb_1.geometry} material={materials.LampBulb} />
      </group>
      <mesh geometry={nodes.StairsSmallNoRail.geometry} material={materials.Wood} position={[0.24, -1.98, -4.09]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[1.8, -1.82, 7.29]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.InteriorWallBasement_1.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.InteriorWallBasement_2.geometry} material={materials.PaintedBricks} />
      </group>
      <mesh geometry={nodes.WaterHeater.geometry} material={materials.WaterHeater} position={[-3.61, -1.82, -5.59]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Truck.geometry} material={materials.Truck} position={[7.68, -0.15, -4.79]} rotation={[Math.PI / 2, 0, -0.37]} />
      <mesh geometry={nodes.Car.geometry} material={materials.Car} position={[18.41, -0.09, 26.23]} rotation={[Math.PI / 2, 0, -0.26]} />
      <group position={[2.03, 3.94, -6.58]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.InteriorWallSupplyCloset_1.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.InteriorWallSupplyCloset_2.geometry} material={materials.InteriorWall} />
      </group>
      <mesh geometry={nodes.Car001.geometry} material={materials['Car.001']} position={[7.62, -0.2, 9.36]} rotation={[Math.PI / 2, 0, -0.26]} />
      <mesh geometry={nodes.Car002.geometry} material={materials['Car.002']} position={[12.86, -0.17, 19.72]} rotation={[Math.PI / 2, 0, 2.39]} />
      <mesh geometry={nodes.Car003.geometry} material={materials['Car.003']} position={[17.92, -0.19, 11.7]} rotation={[Math.PI / 2, 0, -0.23]} />
      <mesh geometry={nodes.Car004.geometry} material={materials['Car.004']} position={[14.33, 0.29, 17.19]} rotation={[1.3, -0.2, -2.25]} />
      <group position={[2.27, 1.29, -2.96]} rotation={[-1.6, 0.99, 0.4]} scale={[-1, -1, -1.06]}>
        <mesh geometry={nodes.DoorRoom001.geometry} material={materials['DoorRoom.001']} />
        <mesh geometry={nodes.DoorRoom001_1.geometry} material={materials['Brass.001']} />
      </group>
      <mesh geometry={nodes.Car005.geometry} material={materials.Car} position={[17.1, -0.32, 60.61]} rotation={[Math.PI / 2, 0, 0.77]} />
      <mesh geometry={nodes.Car006.geometry} material={materials['Car.002']} position={[13.91, -0.54, 55.24]} rotation={[Math.PI / 2, 0, 2.39]} />
      <mesh geometry={nodes.Car007.geometry} material={materials['Car.003']} position={[16.67, -0.13, 46.07]} rotation={[Math.PI / 2, 0, -2.67]} />
      <mesh geometry={nodes.Car008.geometry} material={materials['Car.004']} position={[16.68, -0.01, 53.33]} rotation={[1.3, -0.2, -2.25]} />
    </group>
  )
}



export default MotelObjAdvanced;
useGLTF.preload('/MotelProjetAdvanced.glb')